### PR TITLE
Rebuild for CUDA 12 w/arch support using Gcc11

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Raul! 🙏

It looks like there are conflicts with PR ( https://github.com/conda-forge/torchani-feedstock/pull/24 ), which was recently merged. Would it be possible to fix those?

**Comment by RaulPPelaez** [comment]
Success!

**Comment by jakirkham** [comment]
Thanks Raul! 🙏

@conda-forge/torchani , could you please take a look? 🙂

**Review by yueyericardo — APPROVED** [review]
Thank you so much!

**Comment by jakirkham** [comment]
Thanks Jinze! 🙏

**Pull request merged**
