### PR TITLE
Relax setuptools version in run section

### PR DESCRIPTION
**Pull request by yueyericardo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
Thanks @yueyericardo . Don't forget to bump the build number.

**Comment by yueyericardo** [comment]
@hadim unfortunatly, the test get failed if relax the setuptools version, that probably why I fixed the version: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=462862&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=10344

**Comment by hadim** [comment]
That's too bad. If you can't fix it, then go ahead and let it like that.

Just be aware it might prevent some people using the package in the future.

I suggest putting a note explaining why you are fixing those deps into the recipe file.

**Comment by yueyericardo** [comment]
Yeah, Thanks! I had a note there https://github.com/conda-forge/torchani-feedstock/blob/master/recipe/meta.yaml#L41
Currently we are developing in our interal repo. We will fix this issue when we merge our internal updates to the public in the future.

**Pull request closed without merging**
