### PR TITLE
Relax setuptool run time pins

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Only issues were some downloads from dropbox failing, if this patch fixes them then I will make a PR to get it upstream

**Comment by mikemhenry** [comment]
Sweet! This should fix https://github.com/conda-forge/nnpops-feedstock/pull/39

**Comment by mikemhenry** [comment]
gah another `RuntimeError: Shared memory manager connection has timed out` will kick the build

**Comment by h-vetinari** [comment]
As a maintainer on this feedstock, you can just restart the failed CI jobs (_after_ everything else has run through) using the GH interface for the checks - just click on the red X, and on the left-hand side you'll have a list of jobs with a button next to the failed ones called "Re-run". This avoid having to push spurious commits as well as extra runs for everything that already passed and is therefore highly to be preferred. :)

**Pull request merged**
