### PR TITLE
Manual rebuild pytorch111

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
build logs for https://github.com/conda-forge/torchani-feedstock/pull/8 are dead, using this PR to see if I can fix it

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@hmaarrfk Looks like this is failing for the same reasons that I fixed in  https://github.com/conda-forge/fcos-feedstock/pull/6
but really this should be fixed by upstream... look like it was here: https://github.com/aiqm/torchani/pull/603 
I'll see if they will cut a new release or we might have to patch source so it builds.

**Comment by hmaarrfk** [comment]
Why not back port the patch?

**Comment by mikemhenry** [comment]
I'll give that a shot, I thought that since the last released version was awhile ago that things may have changed too much to make it a simple back port. I'll give it a shot!

**Comment by hmaarrfk** [comment]
Did you ever ask for your release?

**Comment by mikemhenry** [comment]
@hmaarrfk I did, but it was only in a comment in a PR. I will make an issue about a new release + also see if I can cherry-pick the commit into a patch to fix this!

**Comment by mikemhenry** [comment]
@hmaarrfk looks like that fixed it!

**Comment by hmaarrfk** [comment]
Did you want to add yourself as a maintainer?

**Comment by mikemhenry** [comment]
@hmaarrfk yes! good idea, thanks for the remidner!

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
